### ISSUE TITLE
Can you add a short example?

### ISSUE THREAD

**Issue by stuartlynne** [Bluetooth-Devices/bleak-retry-connector#94]
**Is your feature request related to a problem? Please describe.**
Trying to see how this is used. I would like to use it in my projects where I have seen that maintaining a bleak connection is problematic.

**Describe the solution you'd like**
A simple example showing how the bleak-retry-connector is used.

**Comment by bdraco** [comment]
I'd look at all the projects that currently use this library https://github.com/Bluetooth-Devices/bleak-retry-connector/network/dependents

**Comment by jackalsdance** [comment]
For anyone coming here with the same issue that its almost impossible to find an example looking through the dependent projects, look here for someone who has used it: https://github.com/cheadrian/thunderboard-ha/blob/minimal/custom_components/thunderboard/thunderboard_ble/parser.py
